### ISSUE TITLE
Using env.LOKI_SERVER does not seem to work

### ISSUE THREAD

**Issue by valankar** [trea/caddy-loki-logger#4]
I tried to setup an environment variable for the loki server.

```
{
        log default {
                output loki {env.LOKI_SERVER} {
                        label {
                                job caddy
                        }
                }
        }
```

I see this in the logs:

```
{"level":"info","ts":1713374478.7145693,"msg":"redirected default logger","from":"stderr","to":"%7Benv.LOKI_SERVER%7D"} 
```

Whereas normally I would see the URL. Also it seems my Loki server stopped getting any data when I do this.

**Comment by valankar** [comment]
I run Caddy in docker, and when I exec a shell, I can `echo $LOKI_SERVER` and it has the correct URL.

**Comment by trea** [comment]
Try `{$LOKI_SERVER}` instead please

**Comment by valankar** [comment]
Yep, that works!

**Comment by trea** [comment]
Awesome. Thank you for the PR and for the questions!
