### ISSUE TITLE
Large amounts of log data for quiet website

### ISSUE THREAD

**Issue by valankar** [trea/caddy-loki-logger#6]
I've been trying out this logger with Grafana Cloud (thanks for answering questions!). Using it for a few hours showed about 20 GB used on the Grafana console which seemed very high for a very quiet website. Also doing some rate queries in Grafana showed about 6-10 lines per second, and I'm sure my site only gets less than 1 QPS. 

I switched to doing file logging and promtail to ship logs. In that case, the data seemed a lot more reasonable. It's less than 1 per second.

I feel like something was going wrong with this logger and I couldn't really figure out what it was. I didn't really debug too much. Is there any reason why there would be so much data? Is some kind of tracing data also shipped to Loki?

Promtail also lets me take the timestamp from the json and use it as the log timestamp. Promtail has a push API, but I'm not sure if I can use the pipelines to process data coming in that way. I only know it works for file logs.

I can try debugging further, but I wasn't sure how. Thanks.

**Comment by trea** [comment]
A few hours and 20GB doesn't seem possible 😅 If you could provide any additional detail around the configurations you are using, and also what modules you have installed that would be very helpful. The only thing I can think of is just if there's a module installed that is doing like DEBUG level stuff in a loop.

**Comment by valankar** [comment]
I see that Grafana Alloy lets me do relabeling on input coming in via Loki API, so I'll spend some time learning that (only know promtail now). Then I can try debugging this further to see what is being sent by Caddy.

**Comment by valankar** [comment]
Yes something appears quite wrong. From what I can tell, duplicate log lines are sent, just with the json log keys in different order for each request. You can see the rate of logs below just switching to the caddy loki logger from file logger. The duplicate log lines are with the exact same timestamp. I use Grafana Alloy to take the timestamp out from `ts` and store it in the log entry. This works fine when using the file access log.

![volume](https://github.com/trea/caddy-loki-logger/assets/31250800/730a660f-de31-4202-9520-b556d41bc200)
![logs rate](https://github.com/trea/caddy-loki-logger/assets/31250800/23148b8b-a8dc-4a37-adca-290c06a755b2)
![logs detail](https://github.com/trea/caddy-loki-logger/assets/31250800/0a4f2856-c595-447c-8a80-82931d9ff4b2)

I'm building with:

```
RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/lanrat/caddy-dynamic-remoteip \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/trea/caddy-loki-logger
```

And my config is pretty basic with a bunch of websites:

```
{
        log global_access {
                output loki http://localhost:3100 {
                        label {
                                job caddy
                        }
                }
                include http.log.access
        }
}
```

**Comment by valankar** [comment]
I did another test with a simpler configuration, just having Grafana Alloy log to stdout and not changing the log message in any way. This shows the problem a bit better. I ran it for a few seconds and there were 10 identical log lines for 1 request. They all had the exact same ts/timestamp field.

```
$ grep 1713865226.7387235 alloy_logs.txt |wc -l
10
```

I've attached the logs and my sanitized configs.

[alloy_logs.txt](https://github.com/trea/caddy-loki-logger/files/15074948/alloy_logs.txt)
[config.alloy.txt](https://github.com/trea/caddy-loki-logger/files/15074975/config.alloy.txt)
[Caddyfile.txt](https://github.com/trea/caddy-loki-logger/files/15074985/Caddyfile.txt)
[docker-compose.yml.txt](https://github.com/trea/caddy-loki-logger/files/15074996/docker-compose.yml.txt)
[Dockerfile.txt](https://github.com/trea/caddy-loki-logger/files/15075010/Dockerfile.txt)

**Comment by valankar** [comment]
I'm just perusing the code and might be wrong, but:

https://github.com/trea/loki-sink-for-zap/blob/cc5c7f926a9a8b1f10301dbe6d8ed9ce4cd7921b/loki.go#L150

shouldn't `values` here be cleared at some point? I only see an append.

**Comment by valankar** [comment]
Yes I think that is the problem. I debugged a bit more from your loki-sink-for-zap code. In the `TestSetupLoki` test in `loki_test.go` I added some lines:

```
	zlogger := logger.Sugar()

	zlogger.Warnf("Hello from TestSetupLoki 1")
	err = zlogger.Sync()
	zlogger.Warnf("Hello from TestSetupLoki 2")
	err = zlogger.Sync()
	zlogger.Warnf("Hello from TestSetupLoki 3")
	err = zlogger.Sync()
```

and added a `fmt.Print(l.values)` in `prepareForLokiPush`:

```
func (l LokiWriteSyncer) prepareForLokiPush() (io.Reader, error) {
	b := bytes.NewBuffer([]byte{})

	gz := gzip.NewWriter(b)

	fmt.Print(l.values)
...
```

I expected each call to Sync() would output 1 line. Instead, it outputs 1 line, then 2 lines, then 3 lines. Basically it keeps piling the previous logs onto the next sync:

```
vscode ➜ /workspaces/loki-sink-for-zap (main) $ go test -run ^'^TestSetupLoki$'
[[1713882227180427100 {"L":"WARN","T":"2024-04-23T14:23:47.180Z","C":"loki-sink-for-zap/loki_test.go:53","M":"Hello from TestSetupLoki 1","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:53\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
]][[1713882227180427100 {"L":"WARN","T":"2024-04-23T14:23:47.180Z","C":"loki-sink-for-zap/loki_test.go:53","M":"Hello from TestSetupLoki 1","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:53\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
] [1713882227190630917 {"L":"WARN","T":"2024-04-23T14:23:47.190Z","C":"loki-sink-for-zap/loki_test.go:55","M":"Hello from TestSetupLoki 2","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
]][[1713882227180427100 {"L":"WARN","T":"2024-04-23T14:23:47.180Z","C":"loki-sink-for-zap/loki_test.go:53","M":"Hello from TestSetupLoki 1","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:53\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
] [1713882227190630917 {"L":"WARN","T":"2024-04-23T14:23:47.190Z","C":"loki-sink-for-zap/loki_test.go:55","M":"Hello from TestSetupLoki 2","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
] [1713882227192362563 {"L":"WARN","T":"2024-04-23T14:23:47.192Z","C":"loki-sink-for-zap/loki_test.go:57","M":"Hello from TestSetupLoki 3","S":"github.com/trea/loki-sink-for-zap_test.TestSetupLoki\n\t/workspaces/loki-sink-for-zap/loki_test.go:57\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1689"}
]]PASS
ok      github.com/trea/loki-sink-for-zap       0.025s
```

This would explain why my Caddy server kept getting slower and slower and sending more and more data to Loki.

**Comment by trea** [comment]
LMAO this is incredible, thank you so much! I will take a look at this. I haven't actually gotten around to _using_ this module yet if you couldn't tell. Glad I haven't publicized it either 😂

**Comment by valankar** [comment]
No problem. Happy to try again later.

**Comment by trea** [comment]
Thanks again @valankar, this issue should be resolved finally with the latest release. Let me know if/when you try it out!
