### ISSUE TITLE
panic runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by trea** [trea/caddy-loki-logger#7]
https://github.com/caddyserver/caddy/issues/6441 was reported over on the main Caddy repo but was a bug with this module.

@oliemansm I wanted to loop you in here. This issue should now be resolved with the latest release. I _believe_ you were probably getting an error from trying to write to Loki. I actually ran into the error whilst wrapping up some testing for another issue, and it seems like caddy-loki-logger module doesn't actually _have_ a logger to write to if there's an error with the set up. So I have changed it to call the standard library `log.Printf` instead in that case.

So you'll want to monitor the output of your Caddy instance for a `Writing log entry to Loki failed:` error if you decide to use this module again. Feel free to open a new issue or reopen this one as appropriate at that time! Thanks!

**Comment by mholt** [comment]
Thanks for the fix!
